Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disable: true

  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |v| 
    v.memory = 256
    v.linked_clone = true
  end

  # App server 1
  config.vm.define "app" do |app|
    app.vm.hostname = "app.test"
    app.vm.network :private_network, ip: "192.168.56.5"
  end

end
